name: Debug log
on: push
jobs:
    first:
        runs-on: ubuntu-latest
        steps:
        - run: echo sleep 10 && echo "First job completed"
    second:
        runs-on: ubuntu-latest
        needs: [first]
        steps:
        - run: echo sleep 10 && echo "Second job completed"
