name: Share job data
on: push
jobs:
    before:
        runs-on: ubuntu-latest
        steps:
            - id: generate
              run: echo "message=Hello, World!" >> "${GITHUB_OUTPUT}"
        outputs:
            message: ${{ steps.generate.outputs.message }}
    after:
        runs-on: ubuntu-latest
        needs: [before]
        steps:
            - env:
                MESSAGE: ${{ needs.before.outputs.message }}
              run: echo "${MESSAGE}"
